./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/302ai/302_sandbox_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/3rzy/make-mcp-integration-issue
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/adexltd/mcp-google-suite
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/agentience/tribal_mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ai-zerolab/mcp-toolbox
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/aiopinions/TON-ACCESS-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/akaramanapp/weather-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/akazwz/workers-mcp-demo
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/aki-kii/mcp-uuid
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/alexbakers/mcp-ipfs
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/AlexiFeng/MCP_Chat_Logger
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/allen-munsch/mcp-prefect
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/allthatjazzleo/mantrachain-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/amanasmuei/mcp-server-nodemcu
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/amitdeshmukh/stdout-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/andredezzy/deep-filesystem-tree-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/andresthor/cmd-line-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Andrew-Beniash/mcp-command-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/anisirji/mcp-server-remote-setup-with-jwt-auth
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/AntDX316/MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ArchimedesCrypto/figma-mcp-chunked
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/AudienseCo/mcp-tweetbinder
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/awesimon/elasticsearch-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/awslabs/mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Azure-Samples/remote-mcp-functions-typescript
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/bendusy/pollinations-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/billster45/mcp-chatgpt-responses
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/brysontang/DeltaTask
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/buger/docs-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/burkestar/cloudzero-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/cabrit0/mcp_server_reuneMacacada
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/CaChiJ/kakao-navigation-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/chaindead/telegram-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ChiragPatankar/AI-Customer-Support-Bot--MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/chrishayuk/chuk-mcp-time-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/CircleCI-Public/mcp-server-circleci
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/code-yeongyu/perplexity-advanced-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/confluentinc/mcp-confluent
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/CorefluxCommunity/CorefluxMCPServer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/cschmidt0121/splunkbase-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/cso1z/Feishu-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/daniel8824-del/forest-fire-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/devlimelabs/meilisearch-ts-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/devyhan/xcode-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/dhakalnirajan/blender-open-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Dhravya/apple-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Dicklesworthstone/llm_gateway_mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/diegofornalha/mcp-server-tess
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/diegofornalha/mcp-server-trello
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/diez7lm/firestore-advanced-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/disler/aider-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/djbriane/plex-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/djkz/bruno-api-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/DMontgomery40/pentest-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/dncampo/FIWARE-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/emmett-deen/Linear-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/eno-graph/mcp-server-google-analytics
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ErgodicLabs/TwoTruthsAndATwist
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/eternachen/mcp-playground
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/everford/fetcher-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/fakepixels/base-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/FalkorDB/FalkorDB-MCPServer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Faucet94/super-win-cli-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/fdrechsler/mcp-server-idapro
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/felipfr/linkedin-mcpserver
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Fibery-inc/fibery-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/finack/aviation-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/fkesheh/code-context-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/flipt-io/mcp-server-flipt
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/fortunto2/prefect-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/fourcolors/omi-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/FradSer/mcp-server-mas-sequential-thinking
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/freedanfan/mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/FreePeak/db-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/freshlife001/mcp_poker
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Funmula-Corp/BigGo-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/FutureUnreal/mcp-pdf2md
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gabrielmaialva33/mcp-filesystem
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gbti-network/mcp-basic-test
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/GeLi2001/datadog-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/GeLi2001/shopify-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Gertje823/Vinted-Scraper
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ghrud92/loki-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ghubnerr/Notion-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/giannisanni/kokoro-tts-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gitskyflux/cloudtasks-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gitskyflux/firestore-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gmacev/Simple-Memory-Extension-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gofireflyio/firefly-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gojiplus/rmcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/GongRzhe/Langflow-DOC-QA-SERVER
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/GongRzhe/Quickchart-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/goswamig/fetch-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gotalab/bigquery-analysis-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gourav221b/Github-PR-MCP-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gpaul-mcp/MCP_ravelry
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Grandbusta/solana-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/gregkonush/mcp-obsidian
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/GridfireAI/reddit-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/handoing/ig-download-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/HappyAny/latex-mathml-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hardik-id/azure-resource-graph-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Harnishnava/pokemon-ai
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hbg/mcp-paperswithcode
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hectorflores28/mcp-gemini
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hedera-dev/hedera-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hedera-dev/mirrornode-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hetaoBackend/mcp-pyautogui-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hloiseaufcms/mcp-gopls
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/HosakaKeigo/spreadsheet-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hsinyuyen/my-postgres-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hummusonrails/couchbase-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/HundunOnline/mcp-dingdingbot-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/hungthai1401/bruno-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Ichigo3766/powerpoint-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/idofrizler/azure-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/idosal/git-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ifmelate/mcp-image-extractor
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/imax09-wq/mcp-py
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/infinitimeless/claude-lmstudio-bridge
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/InhiblabCore/mcp-image-compression
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/inkeep/mcp-server-python
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/iRahulPandey/PromptLab
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ITworkonline/GoogleCalendarMCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ivanbtrujillo/mcp-server-spike
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/JackKuo666/PubTator-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jackmuva/mcp-actionkit
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/JackXuyi/env-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jae-jae/fetcher-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jagan-shanmugam/open-streetmap-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jakenuts/mcp-cli-exec
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Jaldekoa/mcp-fredapi
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/javaDer/mcp-sentry-custom
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jbchouinard/mcp-document-reader
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jeong-sik/kakao-api-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jhj0517/mcp-python-tutorial
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jlucaso1/whatsapp-mcp-ts
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jmagar/unraid-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jmandel/health-record-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jmh108/md-webcrawl-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/joaowinderfeldbussolotto/MCP-Websearch-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/johnpapa/peacock-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/johwiebe/anki-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jonaolden/pbixray-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/juhemcp/jnews-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jwaxman19/qlik-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jxnl/apple-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/jzinno/biomart-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Kalyankensin/DigitalFate
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/KalyankumarKonduru/MCP_test
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Kirandawadi/volatility3-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kitfactory/PyMCPAutoGUI
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kmexnx/excel-to-pdf-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kmwebnet/MCP-Server-for-sensor-device
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/knight0zh/mssql-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kornbed/jira-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Kotelberg/playwright-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ks0318-p/sound-notification-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ktabori/dixa-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kukapay/blockbeats-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kukapay/crypto-news-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kukapay/freqtrade-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kukapay/hf-trending-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/kuvanov-2/mcp-server-jira
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/L3-N0X/Minecraft-Wiki-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/lanbaoshen/mcp-jenkins
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/LaurieWired/GhidraMCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Leonelberio/the-wordpress-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/leopeng1995/mssql-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/lex-tools/codebase-context-dumper
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/lishenxydlgzs/aws-athena-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/lite/iterm-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/lmcmz/flow-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/lucamauri/MediaWiki-MCP-adapter
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/m-ahmed-elbeskeri/UltimateCoderMCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ma1238906/MCP_Demo
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mailgun/mailgun-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mario-andreschak/mcp-msoffice-interop-word
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/markacianfrani/mcp-notes
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/markvp/mcp-lambda-sam
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/MartinSchlott/BetterMCPFileServer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Maxim2324/mcp-server-test
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mcpdotdirect/evm-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Meeting-Baas/meeting-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/merge-api/merge-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mfangtao/mcp-ssh-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/minio/mcp-server-aistor
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mlobo2012/Claude_Desktop_API_USE_VIA_MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mmruesch12/azdo-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/moekiorg/mcp-auth0-oidc
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mohammeduvaiz/figma-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/MorDavid/BloodHound-MCP-AI
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/MorvanZhou/customized_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/mottibec/israeli-bank-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/MushroomFleet/DeepLucid3D-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/MxIris-Reverse-Engineering/ida-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/nakamurau1/tts-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/naru-sensei/-toast-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/neosapience/typecast-api-mcp-server-sample
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/netwrix/mcp-server-naa
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/NewAITees/TaskMateAI
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/nfshanq/mcp-invoice
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/nguyenlegravityglobal/figma-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/nickclyde/duckduckgo-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Novakiki/mcp-gemini-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Noveum/api-market-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/nrwl/nx-console
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/obre10off/spotify-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/openags/paper-search-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/OpenLinkSoftware/mcp-pyodbc-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/OpenWorkspace-o1/aws-ow-s3-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/opspawn/Google-Flights-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/oraichain/ragflow-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/owayo/gitlab-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/p-funk/FEGIS
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/pab1it0/adx-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/paybyrd/ai-agent-toolkit-js
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/PaymanAI/payman-doc-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/peancor/moodle-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Pedropfuenmayor/mcp-cloudflare
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/phpmac/fetch_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/PoliTwit1984/github-meta-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/pragmar/mcp_server_webcrawl
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Pratik-Kumar-Cse/script-generation-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/priyankark/a11y-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/priyankark/lighthouse-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/PuroDelphi/mcpFirebird
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/pydantic/logfire-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/QAInsights/k6-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/R-lz/mcp-video-digest
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rahgadda/oracledb_mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/RahulRana0707/mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rajbos/ghas-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rakeshgangwar/erpnext-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ramp-public/ramp-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rand-tech/pcm
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/randomm/files-db-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/raoulbia-ai/mcp-server-for-intercom
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/RathodDarshil/mcp-postgres-query-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/reading-plus-ai/mcp-server-deep-research
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/redis/mcp-redis-cloud
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/revit-mcp/revit-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ribeirogab/simple-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rikuson/mcp-qase
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rileyedwards77/perplexity-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rjadhavJT/docgen-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/roboulos/simple-xano-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rohinigaonkar/mcp-math-macos
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ronniemh/phrases-MCP-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rt96-hub/prompt-tester
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ruan11223344/McpDocServer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/runbookai/runbook-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/rvibek/mcp_unhcr
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/RyanCardin15/AzureDevOps-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/s2005/mcp-everything
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/SaintDoresh/Crypto-Trader-MCP-ClaudeDesktop
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/SaintDoresh/YFinance-Trader-MCP-ClaudeDesktop
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sammcj/mcp-aws-kb
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sanketshinde3001/MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sarathsp06/sourcesage
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sasinomalabs/template
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Saunved/mcp-server-clash-of-clans
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/scmdr/sourcesyncai-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/scoutos/mcp-linear
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/scrapeless-ai/scrapeless-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Scrapybara/scrapybara-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/screenshotone/mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sdd330/feishu-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/SecurFi/RapidAPI_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/SepineTam/stata-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/septemhill/etherscan-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sfz009900/kalilinuxmcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/shadi-fsai/fmp_mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/shadowfax92/apple-calendar-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/shanksxz/gh-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/shibuiwilliam/mcp-server-data-wrangler
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/shinzo-labs/gmail-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/shiquda/mediawiki-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Shopify/dev-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Shy2593666979/mcp-server-email
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sichang824/mcp-terminal
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sinedied/grumpydev-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sirusb/samtools_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Sjotie/notionMCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sjquant/llm-bridge-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Skywalker-Harrison/mcp-soduku
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/SlideSpeak/slidespeak-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/smian0/mcp-agile-flow
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sparesparrow/mcp-project-orchestrator
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/speakeasy-api/markdown-sidecar-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/spences10/mcp-turso-cloud
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Srish-ty/MCP-Testing-interface-for-LLMs
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/stabgan/openrouter-mcp-multimodal
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/stanislavlysenko0912/todoist-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/StdioA/beancount-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/surya-madhav/MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/susheel/synapse-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sworddut/mcp-ffmpeg-helper
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/syahiidkamil/mcp-postgres-full-access
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/sylphlab/filesystem-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Sysc4lls/IDA-doc-hint-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Szowesgad/mcp-server-semgrep
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/taazkareem/clickup-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/taazkareem/twitter-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/taiste/harvest-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/talhaorak/pytaiga-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tan-yong-sheng/triliumnext-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tanob/mcp-desktop-automation
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tddt/stock_info_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/techkwon/mcp-gemini
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tembo-io/mcp-server-tembo
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/TencentEdgeOne/edgeone-pages-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/TeXmeijin/manalinkMCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Tght1211/http-4-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/TheRaLabs/legion-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/thirdstrandstudio/mcp-figma
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/thirdstrandstudio/mcp-xpath
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/thisnick/google-calendar-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/thomasdavis/blah
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ThreatFlux/YaraFlux
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Timandes/mcp-gateway
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tinyfish-io/agentql-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tisDDM/searxng-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tmhr1850/backlog-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tobecrazy/MCPDemo
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/torshepherd/compiler-explorer-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/totto2727-org/mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/translated/lara-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/triptych/opera-omnia-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Tritlo/lsp-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tuanle96/mcp-github
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/twodoorsdev/react-native-debugger-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/twolven/mcp-stockflow
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Tzott/apifox-mcp-demo
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Ujjawal-Rajput/mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/UserAd/didlogic_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/utkucy/avalanche-mcp-tools
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vakharwalad23/google-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vasstavkumar/weather-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/veenastudio/flstudio-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vinayak-mehta/linear-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vishalsachdev/eventbrite-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vivekhaldar/emacs-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wangtsiao/pulse-cn-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wesnermichel/nexus-mcp-claude-desktop-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wilsonchenghy/ShaderToy-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/win4r/browser-use-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wolfyy970/docs-fetch-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wukan1986/mcp_query_table
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/X3r0K/BurpSuite-MCP-Server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/x51xxx/osp-marketing-tools-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/XD3an/mcp-builder
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xiaolaa2/ableton-copilot-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xxflux/figma_MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yamadashy/repomix
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yannbam/bash-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yannbam/fresh-js-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/YCloud-Developers/ycloud-whatsapp-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yisu201506/mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yokingma/time-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yorrickjansen/strava-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yting27/weather-my-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yuna0x0/anilist-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yuna0x0/hackmd-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yunwoong7/aws-nova-canvas-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/z9905080/mcp-langfuse
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zbkm/mmnt-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ZedMoster/revit-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zerubroberts/safetyculture-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zhaoxin34/mcp-server-mysql
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zhaoyouj/mcp-slicer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zhixiaoqiang/desktop-image-manager-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zhongmingyuan/mcp-my-mac
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ZizoTheDev/ffmpeg-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ZNCOU/mcp-installer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zxfgds/mcp-toolkit
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/Zzzccs123/mcp-sentry
